version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 324037310518.dkr.ecr.ap-southeast-1.amazonaws.com
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $AWS_ECR_NAME:latest .
      - docker tag $AWS_ECR_NAME:latest $AWS_ECR_URI/$AWS_ECR_NAME:latest
      - docker tag $AWS_ECR_NAME:latest $AWS_ECR_URI/$AWS_ECR_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to AWS ECR 
      - docker push $AWS_ECR_URI/$AWS_ECR_NAME:latest
      - docker push $AWS_ECR_URI/$AWS_ECR_NAME:$IMAGE_TAG
artifacts:
  files:
    - appspec.yml
    - scripts/start-process.sh